POST http://localhost:3000/Batch/NewBatch
Content-Type: application/json

{
 "Batch_ID":"R20-2022",
 "Batch_Name":"R202022 Batch",
 "Academic_Year":[2022,2025],
 "Regulation_ID":"R20"
}

###
GET http://localhost:3000/Batch


###

Get http://localhost:3000/Batch/R20-2022