POST http://localhost:3000/Batch/NewBatch
Content-Type: application/json

{
 "Batch_ID":"R15-2005",
 "Batch_Name":"R152005 Batch",
 "Academic_Year":2005,
 "Regulation_ID":"R15"
}

###
GET http://localhost:3000/Batch


###

Get http://localhost:3000/Batch/