POST http://localhost:3000/Department/New_Department
Content-Type: application/json

{
    "Department_ID":"00PH",
    "Department_Name":"Physics"
}


###

GET http://localhost:3000/Department

###
GET http://localhost:3000/Department/00IT




# ------------------------------------------------
###
POST https://university-app-2021.herokuapp.com/Department/New_Department

Content-Type: application/json

{
    "DEPARTMENT_ID":"AI",
    "DEPARTMENT_NAME":"artificial intelligence",
    "INSTITUTION_ID":
}
