POST http://localhost:3000/Department/New_Department
Content-Type: application/json

{
    "Department_ID":"00PH",
    "Department_Name":"Physics"
}


###

GET http://localhost:3000/Department

###
GET http://localhost:3000/Department/00IT


