POST http://localhost:3000/Regulation/New_Regulation
content-type: application/json

{
    "Regulation_Name":"R6",
    "Regulation_ID":"R06",
    "Academic_Year":[2012,
    2016]
}

###
GET http://localhost:3000/Regulation

###
DELETE http://localhost:3000/Regulation/Delete_Regulation/R06


###
GET http://localhost:3000/Regulation/R03
 
###
PUT http://localhost:3000/Regulation/Update_Regulation/R5
content-type: application/json

{
    "Regulation_Name":"R5",
    "Regulation_Id":"R5",
    "Academic_Year":[2010,2014],
    "Department_Details":
[
{
    "Department_ID":"AI",
    "Department_Name":"artificial intelligence",
    "total_Credit":15,
    "Semester_Count":3,
    "Credits_Details":
    [
        { "sNo": 1, "Core": 4, "OE": 4, "PE": 4 },
    { "sNo": 2, "Core": 4, "OE": 4, "PE": 4 },
    { "sNo": 3, "Core": 4, "OE": 4, "PE": 4 }   

    ]

},
{
    "Department_ID":"IT",
    "Department_Name":"Informaton Technology",
    "total_Credit":15,
    "Semester_Count":3,
    "Credits_Details":
    [
        { "sNo": 1, "Core": 4, "OE": 4, "PE": 4 },
    { "sNo": 2, "Core": 4, "OE": 4, "PE": 4 },
    { "sNo": 3, "Core": 4, "OE": 4, "PE": 4 }   

    ]

}
]

}



###

post http://localhost:3000/Regulation/New_Regulation
content-type: application/json

{
"Regulation_ID":"R11",
"Regulation_Name":"R11",
"Academic_Year":[2016,2020],
"Department_Details":
[
{
    "Department_ID":"AI",
    "Department_Name":"artificial intelligence",
    "total_Credit":15,
    "Semester_Count":3,
    "Credits_Details":
    [
        { "sNo": 1, "Core": 4, "OE": 4, "PE": 4 },
    { "sNo": 2, "Core": 4, "OE": 4, "PE": 4 },
    { "sNo": 3, "Core": 4, "OE": 4, "PE": 4 }   

    ]

},
{
    "Department_ID":"IT",
    "Department_Name":"Informaton Technology",
    "total_Credit":15,
    "Semester_Count":3,
    "Credits_Details":
    [
        { "sNo": 1, "Core": 4, "OE": 4, "PE": 4 },
    { "sNo": 2, "Core": 4, "OE": 4, "PE": 4 },
    { "sNo": 3, "Core": 4, "OE": 4, "PE": 4 }   

    ]

}
]


}



###  
get http://localhost:3000/Regulation/R11


### 
POST https://university-app-2021.herokuapp.com/Regulation/New_Regulation
content-type: application/json

{
"Regulation_ID":"R1",
"Regulation_Name":"R1",
"Academic_Year":[2010,2014],
"Department_Details":
[
{
    "Department_ID":"AI",
    "Department_Name":"artificial intelligence",
    "total_Credit":15,
    "Semester_Count":3,
    "Credits_Details":
    [
        { "sNo": 1, "Core": 4, "OE": 4, "PE": 4 },
    { "sNo": 2, "Core": 4, "OE": 4, "PE": 4 },
    { "sNo": 3, "Core": 4, "OE": 4, "PE": 4 }   

    ]

},
{
    "Department_ID":"IT",
    "Department_Name":"Informaton Technology",
    "total_Credit":15,
    "Semester_Count":3,
    "Credits_Details":
    [
        { "sNo": 1, "Core": 4, "OE": 4, "PE": 4 },
    { "sNo": 2, "Core": 4, "OE": 4, "PE": 4 },
    { "sNo": 3, "Core": 4, "OE": 4, "PE": 4 }   

    ]

}
]


}

 


###
//---------------updated Design---------------------------------------------------------------------------------------

post http://localhost:3000/Regulation/newregulation/IN0010
Content-Type: application/json

{
"Regulation":
[
    {
    "Active":true,
    "Regulation_ID":"R2",
    "Regulation_Name":"R2",
    "Academic_Year":[2020],
    "Grading":
        {
        "GradeType":"Points",
        "RangeLow":5,
        "RangeHigh":8,
        "GradingDetails":
        [
            {
            "point" : 10,
            "grade" : "O",
            "description" : "Excellent",
            "percentage" : 95
            }
        ,
            {
            "point" : 9,
            "grade" : "A+",
            "description" : "Very Good",
            "percentage" : 85
            }
        ,
            {
            "point" : 8,
            "grade" : "A",
            "description" : "Good",
            "percentage" : 75
        },{
            "point" : 7,
            "grade" : "B+",
            "description" : "Bad",
            "percentage" : 65
        }

]



},
"Department_Details":[
{
    "Department_ID":"AI",
    "Department_Name":"artificial intelligence",
    "Total_Credit":15,
    "Semester_Count":3,
    "Credits_Details":
    [
        { "sNo": 1, "Core": 4, "OE": 4, "PE": 4 },
    { "sNo": 2, "Core": 4, "OE": 4, "PE": 4 },
    { "sNo": 3, "Core": 4, "OE": 4, "PE": 4 }   

    ]

},
{
    "Department_ID":"IT",
    "Department_Name":"Informaton Technology",
    "Total_Credit":15,
    "Semester_Count":3,
    "Credits_Details":
    [
        { "sNo": 1, "Core": 4, "OE": 4, "PE": 4 },
    { "sNo": 2, "Core": 4, "OE": 4, "PE": 4 },
    { "sNo": 3, "Core": 4, "OE": 4, "PE": 4 }   

    ]

}
]
}
]  
}


###
get http://localhost:3000/Regulation/getregulation

###
get http://localhost:3000/Regulation/getregulation/IN0010

###
get http://localhost:3000/Regulation/getdepartmentdetailsbyid/IN0010/R1