GET  http://localhost:3000/Subject


###
POST   http://localhost:3000/Subject/NewSubject/1/1/1/7
Content-Type: application/json

{
"Subject_ID":"SUB7",
"Subject_Name":"Computer Graphics",
"isActive":true,
"Type":"core",
"Department_ID":"1",
"Regulation_ID":"R2",
"Credit":"4"
} 


###

GET http://localhost:3000/Subject/GetSubjectByID/15MA007

###
PUT http://localhost:3000/Subject/UpdateSubject/15I001
Content-Type:application/json

{
"Subject_ID":"15I001",
"Subject_Name":"Data Structure",
"isActive":true,
"Type":"OE",
"Department_ID":"00IT",
"Regulation_ID":"R2",
"Credit":"4"
}

###
DELETE http://localhost:3000/Subject/Delete_Subject/15I010










###
POST   http://localhost:3000/Subject/MultipleSubject
Content-Type: application/json

[
{
"Subject_ID":"15MA008",
"Subject_Name":"Calculus",
"isActive":true,
"Type":"core",
"Department_ID":"00Maths",
"Regulation_ID":"R2",
"Credit":"4"
},
{
      "Subject_ID": "15I010",
      "Subject_Name": "Advanced Data Structure",
      "isActive": true,
      "Type": "core",
      "Department_ID": "00IT",
      "Regulation_ID": "R2",
      "Credit": "4",
      "__v": 0
    }

]

###






//heroku services


POST   https://hidden-sierra-56427.herokuapp.com/Subject/MultipleSubject
Content-Type: application/json

[
{
"Subject_ID":"15MA008",
"Subject_Name":"Calculus",
"isActive":true,
"Type":"core",
"Department_ID":"00Maths",
"Regulation_ID":"R2",
"Credit":"4"
},
{
      "Subject_ID": "15I010",
      "Subject_Name": "Advanced Data Structure",
      "isActive": true,
      "Type": "core",
      "Department_ID": "00IT",
      "Regulation_ID": "R2",
      "Credit": "4",
      "__v": 0
    }

]


###
# --------------------------------------------------------updated design----------------------------------------------------------------------------

Post   http://localhost:3000/Subject/addsubject/IN0010/R2/CR0005
Content-Type: application/json

[
{

  "Subject_ID":"02",
  "Subject_Name":"C Basic",
  "isActive":true,
  "Type":"Core",
  "Credit":4
},
{

  "Subject_ID":"03",
  "Subject_Name":"Engineer Drawing",
  "isActive":true,
  "Type":"PE",
  "Credit":2
},
{

  "Subject_ID":"03",
  "Subject_Name":"Engineer Graphics",
  "isActive":true,
  "Type":"PE",
  "Credit":2
}
,
{

  "Subject_ID":"04",
  "Subject_Name":"Thermodynamics",
  "isActive":true,
  "Type":"Core",
  "Credit":4
}
,
{

  "Subject_ID":"05",
  "Subject_Name":"Fluid Mechanics",
  "isActive":true,
  "Type":"OE",
  "Credit":2
}
]


###
PUT http://localhost:3000/Subject/editsubject/IN0010/R1/AI/02
Content-Type: application/json

 {

      "Subject_ID": "02",
      "Subject_Name": "Data Control",
      "isActive": true,
      "Type": "OE",
      "Credit": 2
}
###
###

GET http://localhost:3000/Subject/getsubjectbyid/IN0010/R1/CR0001/01

###
GET http://localhost:3000/Subject/getsubject/IN0010/R2/CR0005

###
PATCH http://localhost:3000/Subject/saveSkeletonToSubject/IN0010/R1/CR0001/CR02/1/15AI001
Content-Type : application/json

{
  "subject_type": "Theory",
        "total_marks_subject": 100,
        "passing_percentage": 40,
        "subject_contributors": [
            {
                "sNo": 1,
                "type_of_evaluation": "Attendance",
                "total_marks": 10,
                "individual_contribution": 5
            },
            {
                "sNo": 2,
                "type_of_evaluation": "Internal Assessment 1",
                "total_marks": 15,
                "individual_contribution": 7.5
            },
            {
                "sNo": 3,
                "type_of_evaluation": "Internal Assessment 2",
                "total_marks": 15,
                "individual_contribution": 7.5
            },
            {
                "sNo": 4,
                "type_of_evaluation": "Assignment",
                "total_marks": 10,
                "individual_contribution": 5
            },
            {
                "sNo": 5,
                "type_of_evaluation": "Final Evaluation",
                "total_marks": 100,
                "individual_contribution": 70
            },
            {
                "sNo": 6,
                "type_of_evaluation": "Custom Evaluation",
                "total_marks": 10,
                "individual_contribution": 5
            }
        ]
}
